In [1]:
from scripts.conf_file_finding import try_find_conf_file
try_find_conf_file()

Local configuration file found !!, no need to run the configuration (unless configuration has changed)


In [2]:
import datajoint as dj
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import u19_pipeline.ephys_pipeline as ep
import u19_pipeline.utils.ephys_utils as eu
import u19_pipeline.utils.DemoReadSGLXData.readSGLX as readSGLX


from u19_pipeline import recording



c:\Users\MiniVR-8\miniconda3\envs\u19_pipeline_python_env\Lib\site-packages\datajoint\plugin.py:4: UserWarning: Module scripts was already imported from None, but c:\experiments\u19-pipeline-python is being added to sys.path
  import pkg_resources
[2025-12-01 16:28:06,413][INFO]: DataJoint 0.14.6 connected to u19prod@datajoint00.pni.princeton.edu:3306


In [3]:
behavior = dj.create_virtual_module('behavior', 'u19_behavior')
ephys_pipeline = dj.create_virtual_module('ephys_pipeline', 'u19_ephys_pipeline')

In [6]:
recording_synced = (ep.BehaviorSync & "sync_data is not null").fetch('KEY', 'sync_data', order_by='recording_id DESC', as_dict=True)

In [9]:
for rec_key in recording_synced:

    print('rec_key', rec_key['recording_id'])

    update_key = dict()
    update_key['recording_id'] = rec_key['recording_id']
    if rec_key['sync_data']['regular_sync_status']:
        update_key['regular_sync_status'] = 1
        update_key['fixed_sync_status'] = 0
    else:
        update_key['regular_sync_status'] = 0
        update_key['fixed_sync_status'] = 1

    if rec_key['sync_data']['virmen_sync_status']:
        update_key['virmen_sync_status'] = 1
    else:
        update_key['regular_sync_status'] = 0

    print('update_key', update_key)
    break

    #(ephys_pipeline.BehaviorSync).update1(update_key)
    


rec_key 524
update_key {'recording_id': np.int64(524), 'regular_sync_status': 1, 'fixed_sync_status': 0, 'virmen_sync_status': 1}


In [13]:
rec_key['sync_data']['trial_idx_vector'].shape

(380,)

In [15]:
rec_key['sync_data']['iteration_idx_vector']

[array([ 75604,  75729,  75755, ..., 212266, 212308, 213910], shape=(3202,)),
 array([213979, 214107, 214140, ..., 293274, 293315, 294576], shape=(1889,)),
 array([294670, 294795, 294819, ..., 352070, 352111, 353645], shape=(1324,)),
 array([353711, 353833, 353859, ..., 435161, 435204, 436419], shape=(1942,)),
 array([436482, 436610, 436636, ..., 494334, 494376, 495601], shape=(1334,)),
 array([495667, 495790, 495833, ..., 609761, 609801, 611354], shape=(2722,)),
 array([611419, 611546, 611571, 611598, 611636, 611680, 611720, 611762,
        611803, 611845, 611885, 611929, 611970, 612012, 612053, 612093,
        612137, 612178, 612219, 612261, 612302, 612345, 612387, 612428,
        612470, 612511, 612552, 612594, 612636, 612678, 612719, 612762,
        612807, 612852, 612930, 612964, 612999, 613034, 613069, 613104,
        613138, 613177, 613219, 613260, 613302, 613345, 613386, 613427,
        613470, 613512, 613553, 613595, 613636, 613679, 613720, 613762,
        613803, 613846, 6138